# Generated by Django 6.0.4 on 2026-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_face_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
