# Generated by Django 5.1.2 on 2026-04-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_face_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_absent', models.BooleanField(default=True, help_text='Send email when marked absent')),
                ('email_on_below_threshold', models.BooleanField(default=True, help_text='Send email when attendance below threshold')),
                ('email_frequency', models.CharField(choices=[('immediately', 'Immediately'), ('daily', 'Daily (once per day)'), ('weekly', 'Weekly (once per week)')], default='daily', max_length=20)),
                ('sms_enabled', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_on_absent', models.BooleanField(default=False)),
                ('sms_on_below_threshold', models.BooleanField(default=False)),
                ('notify_parent', models.BooleanField(default=False)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='e.g., 22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='e.g., 08:00', null=True)),
                ('alerts_disabled', models.BooleanField(default=False)),
                ('disabled_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preference', to='attendance.student')),
            ],
            options={
                'verbose_name_plural': 'Alert Preferences',
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('absent', 'Marked Absent'), ('below_threshold', 'Below Attendance Threshold')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('current_attendance', models.FloatField(blank=True, null=True)),
                ('classes_needed', models.IntegerField(blank=True, null=True)),
                ('threshold', models.IntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to='attendance.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Alert Created'), ('sent', 'Alert Sent'), ('failed', 'Alert Failed'), ('retried', 'Alert Retried'), ('expired', 'Alert Expired')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='attendance.attendancealert')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyAlertLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('absent_alerts_sent', models.IntegerField(default=0)),
                ('threshold_alerts_sent', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_alert_limits', to='attendance.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['student', '-created_at'], name='attendance__student_9d184e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['status', 'created_at'], name='attendance__status_98b6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['alert', '-timestamp'], name='attendance__alert_i_c471ab_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyalertlimit',
            index=models.Index(fields=['student', 'date'], name='attendance__student_d783a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyalertlimit',
            unique_together={('student', 'date')},
        ),
    ]
