# Generated by Django 5.1.2 on 2025-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_date_alter_attendance_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="face_embedding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
